services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=numeros-y-futbol
      - DB_USER=numeros
      - DB_PASS=Info2026/*-
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=alejo.sotomayor0411@gmail.com
      - SMTP_PASS=edwckmhhfljuzkcj
      - SMTP_FROM_NAME=Números y Fútbol
    volumes:
      - uploads:/var/www/html/backend/uploads
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
      - TZ=America/El_Salvador
      - MARIADB_ROOT_PASSWORD=root2026
      - MARIADB_DATABASE=numeros-y-futbol
      - MARIADB_USER=numeros
      - MARIADB_PASSWORD=Info2026/*-
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  dbdata:
  uploads:
